### ISSUE TITLE
打开浏览器控制台之后找不到NotionPlus扩展程序

### ISSUE THREAD

**Issue by PanZiwei** [mayneyao/NotionPlus#3]
你好，我已成功安装NotionPlus插件。但是在浏览器控制台中的Top下拉菜单里无法找到NotionPlus，请问应该如何解决？
<img width="547" alt="Screen Shot 2020-01-27 at 22 15 10" src="https://user-images.githubusercontent.com/44417006/73232838-a0da3480-4152-11ea-9c32-11028a306862.png">
<img width="1345" alt="Screen Shot 2020-01-27 at 22 14 52" src="https://user-images.githubusercontent.com/44417006/73232844-a33c8e80-4152-11ea-97d3-64323126a986.png">

**Comment by mayneyao** [comment]
扩展只在 notion.so 域名下启用生效，去 notion 页面打开 dev tools 即可。
